### ISSUE TITLE
Ссылка на библиотеку mcp_can

### ISSUE THREAD

**Issue by Ivan-NN** [KruFFT/CAN-Sniffer#1]
Добрый день. Дайте, пожалуйста, ссылку на библиотеку mcp_can, которая используется в проекте.

**Comment by kvaga** [comment]
Да, поддерживаю. Дайте, пожалуйста

**Comment by baziliolg** [comment]
Вот эта библиотека: https://github.com/Seeed-Studio/CAN_BUS_Shield

**Comment by KruFFT** [comment]
Обновил Arduino код до поддержки актуальной версии CAN-BUS Shield 2.3.1.
