### ISSUE TITLE
Ошибка компиляции.

### ISSUE THREAD

**Issue by kseregan** [KruFFT/CAN-Sniffer#4]
Добрый день, KruFFT. Попробовал реализовать Ваш проект на ESP8266. Есть проблема в части нахождения библиотек...
Среда разработки ругается на отсутствие библиотек, я нашел библиотеку MCP2515 для ESP8266/ESP32 - c ней компилятор доходит до проверки библиотеки "MCP2515.h" , однако в ней есть подключаемая библиотека "driver/spi-master.h" и естественно выходит ошибка в компиляторе:

In file included from C:\Users\Сергей\Documents\Arduino\CANSnifer\CANSnifer.ino:2:
mcp2515.h:4:10: **fatal error: driver/spi_master.h: No such file or directory**
    4 | #include "driver/spi_master.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1
driver/spi_master.h: No such file or directory

Ошибка компиляции для платы NodeMCU 1.0 (ESP-12E Module).

Просьба указать дать ссылку на библиотеки для проекта. или по возможности дать ссылку на "правильную" библиотеку  MCP2515.h под Ваш проект. Заранее благодарю.
![Снимок](https://user-images.githubusercontent.com/87333692/189516562-869f43cd-98f6-49f7-af50-a11cc64f928e.PNG)

**Comment by kseregan** [comment]
Проблема решена. Вопрос закрыт.

**Comment by KruFFT** [comment]
Добрый день.
Эх, не успел :) Ну хорошо, что получилось разобраться.
