### ISSUE TITLE
test packet sending wxCAN Sniffer 2.1.0

### ISSUE THREAD

**Issue by andreypav2** [KruFFT/CAN-Sniffer#6]
Hello!
Thank you for you work!
In the new version wxCAN Sniffer 2.1.0 the sending test packet is not work
Could you please look at it
Add interval sending packet also would be highly appreciated

**Comment by KruFFT** [comment]
Hi.
The problem was in PC application. I have updated [develop](https://github.com/KruFFT/wxCAN-Sniffer/commits/develop/) branch with fix today.

**Comment by KruFFT** [comment]
Hi again.
Fixed in version [2.1.1](https://github.com/KruFFT/wxCAN-Sniffer/releases).
